Find the shape, size and dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [6]:
import numpy as np
a=np.array([[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]])
        
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [9]:
np.shape(a) # to find shape of an array

(3, 4)

In [11]:
np.ndim(a) # to find the dimention of an array

2

In [13]:
np.size(a) #to find the size of an array

12

Write python code to access the first row of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]


In [17]:
import numpy as np
b=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b[0]           #we accessed the 1st row

array([1, 2, 3, 4])

5. How do you access the element at the third row and fourth column from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [18]:
import numpy as np
c=np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
c[2][3]

12

6. Write code to extract all odd-indexed elements from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [21]:
import numpy as np
d=np.array( [[1, 2, 3, 4],[5, 6, 7, 8], [9, 10, 11, 12]])
d[:,1::2].flatten()

array([ 2,  4,  6,  8, 10, 12])

7. How can you generate a random 3x3 matrix with values between 0 and 1?


In [28]:
import numpy as np
a=np.random.rand(3,3)
a

array([[0.70781666, 0.96125247, 0.6184828 ],
       [0.47771728, 0.35459035, 0.24430854],
       [0.91964571, 0.48637903, 0.24715865]])

9. Write code to increase the dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [32]:
import numpy as np
a=np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b=np.expand_dims(a,axis=0)
b

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

10. How to transpose the following array in NumPy?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [34]:
import numpy as np
a=np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a=a.T
a

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

11. Consider the following matrix:
Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

In [36]:
import numpy as np        #index wise multiplication
a=np.array( [[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])
b=np.array([[1, 2, 3, 4] ,[5, 6, 7, 8],[9, 10, 11, 12]])
a*b

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [39]:
#matrix multiplication
import numpy as np 
a=np.array( [[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])
b=np.array([[1, 2, 3, 4] ,[5, 6, 7, 8],[9, 10, 11, 12]])
result=np.dot(a,b.T)
result2=a@b.T
result

array([[ 30,  70, 110],
       [ 70, 174, 278],
       [110, 278, 446]])

In [40]:
#add both the matrics
import numpy as np 
a=np.array( [[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])
b=np.array([[1, 2, 3, 4] ,[5, 6, 7, 8],[9, 10, 11, 12]])
a+b

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [41]:
#sub matrix b from a
import numpy as np 
a=np.array( [[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])
b=np.array([[1, 2, 3, 4] ,[5, 6, 7, 8],[9, 10, 11, 12]])
b-a

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [42]:
#divide matrix b from a
import numpy as np 
a=np.array( [[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])
b=np.array([[1, 2, 3, 4] ,[5, 6, 7, 8],[9, 10, 11, 12]])
b/a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])